<main class="container">
    <h2><i class="fas fa-pencil-alt"></i>Rédiger un nouvel article</h2>
    <form action="form.php" method="POST">
        <fieldset>
            <legend><i class="far fa-file"></i>Nouvel Article</legend>
        
            <ul class='list'>
                <li>
                    <label for="title">Title :</label>
                    <input type="text" id="title" name="title">
                </li>
                <li>
                    <label for="contents">Article :</label>
                    <textarea id="contents" name="contents" row="50"></textarea>
                </li>
                <li>
                    <label for="author">Author :</label>
                    <select id="author" name="author">
                        <?php foreach ($authors as $author): ?>
                            <option value="<?=$author['Id']?>"><?= $author['FirstName'].' '.$author['LastName']?></option>
                        <?php endforeach ?>
                    </select>
                </li>
                <li>
                    <label for="category">Category :</label>
                    <select id="category" name="category">
                        <?php foreach ($categories as $category): ?>
                            <option value="<?=$category['Id']?>"><?= $category['Name']?></option>
                        <?php endforeach ?>
                    </select>
                </li>
                <li>
                    <button class="button button_submit" type="submit">Enregistrer</button>
                    <a class="button button_cancel link" href="admin.php">Annuler</a>
                </li>
            </ul>
        </fieldset>
        
    </form>
</main>