<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="../CSS/normalize.css">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Dosis" rel="stylesheet">
    <link rel="stylesheet" href="../CSS/index.css">
    <title>Blog</title>
</head>
<body>
    <header>
        <h1><a href="../index.php" class="link"><i class="fas fa-microphone"></i>Encore un blog ?!</a></h1>
        <?php if ($_SESSION != null ) { ?>
            <p id="messageWelcome">Bienvenue <?=$_SESSION['pseudo']?></p>
        <?php } ?>
        <nav>
            <?php if ($_SESSION == null ) { ?>
                <a href="register.php" class="link" id="linkRegister"><i class="fas fa-user-plus"></i>Register</a>
                <a href="login.php" class="link" id="linkLogin"><i class="fas fa-sign-in-alt"></i>Sign In</a>
            <?php } ?>

            <?php if ($_SESSION != null && $_SESSION['role'] == 'admin') { ?>
                <a href="admin.php" class="link" id="linkAdmin"><i class="fas fa-cogs"></i>Administration</a>
            <?php } ?>

            <?php if ($_SESSION != null ) { ?>
                <a href="logout.php" class="link" id="linkLogout"><i class="fas fa-sign-out-alt"></i>Sign Out</a>
            <?php } ?>
            
        </nav>
    </header>
    