<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="CSS/normalize.css">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Dosis" rel="stylesheet">
    <link rel="stylesheet" href="CSS/index.css">
    <title>Blog</title>
</head>
<body>
    <header>
        <h1><a href="index.php" class="link"><i class="fas fa-microphone"></i>Encore un blog ?!</a></h1>
        <?php if ($_SESSION != null ) { ?>
            <p id="messageWelcome">Bienvenue <?=$_SESSION['pseudo']?></p>
        <?php } ?>
        <nav>
            <?php if ($_SESSION == null ) { ?>
                <a href="PHP/register.php" class="link" id="linkRegister"><i class="fas fa-user-plus"></i>Register</a>
                <a href="PHP/login.php" class="link" id="linkLogin"><i class="fas fa-sign-in-alt"></i>Sign In</a>
            <?php } ?>

            <?php if ($_SESSION != null && $_SESSION['role'] == 'admin') { ?>
                <a href="PHP/admin.php" class="link" id="linkAdmin"><i class="fas fa-cogs"></i>Administration</a>
            <?php } ?>
            
            <?php if ($_SESSION != null ) { ?>
                <a href="PHP/logout.php" class="link" id="linkLogout"><i class="fas fa-sign-out-alt"></i>Sign Out</a>
            <?php } ?>
            
        </nav>
    </header>

<main class="container">
    <h2><i class="fas fa-home"></i>Accueil</h2>
    <ul class="article">
        <li class="list">
            <?php foreach ($articles as $article) { ?>
                <h3><i class="far fa-hand-point-right"><a href="PHP/article.php?Id=<?=$article['Id']?>" class="link" id="<?=$article['Id']?>"></i><?= htmlspecialchars($article['Title'])?></a></h3>
                 
                <?php if ( strlen($article['Contents']) < 15 ) { ?>
                    <p><?= htmlspecialchars($article['Contents'])?></p>
                <?php } else { ?>
                    <p><?= htmlspecialchars(substr($article['Contents'],0,15))?> [...]</p>
                <?php } ?>
                
                <p>Rédigé par <?=$article['FirstName'].''.$article['LastName']?> le <?=$article['CreationDate']?> </p>

            <?php } ?>    
         
        </li>
    </ul>
</main>