<main class="container">
<h2><i class="fas fa-sign-in-alt"></i>S'identifier</h2>

<?php if ($error == true ) {?>
    <div class="popup">
        <p> <?= $message ?></p>
    </div>
<?php } ?>

<form action="login.php" method="POST">
            <fieldset>
                <legend><i class="far fa-file"></i>Sign In</legend>
            
                <ul class='list loginForm'>
                    <li>
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email">
                    </li>
                    <li>
                        <label for="password">Mot de passe :</label>
                        <input type="text" id="password" name="password">
                    </li>
                    <li>
                        <button class="button button_submit" type="submit">Enregistrer</button>
                        <a class="button button_cancel link" href="index.php">Annuler</a>
                    </li>
                </ul>
            </fieldset>
            
    </form>




</main>