<main class="container">
    <h2><i class="fas fa-pencil-alt"></i>Editer un article</h2>

    <form action="modifArticle.php?Id=<?=$_GET['Id']?>" method="POST">
        <fieldset>
            <legend><i class="far fa-file"></i>Article</legend>
            <ul class="list">
                <li>
                    <label for="title">Title</label>
                    <input type="text" name="title" value="<?=$InfosArticle['Title']?>">
                </li>
                <li>
                    <label for="article">Article</label>
                    <textarea name="contents"  rows="50"><?=$InfosArticle['Contents']?></textarea>
                </li>
                <li>
                    <button class="button button_submit" type="submit">Mettre à jour</button>
                    <a class="button button_cancel link" href="admin.php">Annuler</a>
                </li>
            </ul>
        </fieldset>
    </form>
</main>