<main class="container">
    <h2><i class="fas fa-user-plus"></i>S'enregistrer</h2>
    
    <form action="register.php" method="POST">
            <fieldset>
                <legend><i class="far fa-file"></i>Nouvel Utilisateur</legend>
            
                <ul class='list registerForm'>
                    <li>
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email">
                    </li>
                    <li>
                        <label for="password">Mot de passe :</label>
                        <input type="text" id="password" name="password">
                    </li>
                    <li>
                        <label for="name">Nom :</label>
                        <input type="text" id="name" name="name">
                    </li>
                    <li>
                        <label for="firstname">Prénom :</label>
                        <input type="text" id="firstname" name="firstname">
                    </li>
                    <li>
                        <label for="pseudo">Pseudo :</label>
                        <input type="text" id="pseudo" name="pseudo">
                    </li>
                    <li>
                        <button class="button button_submit" type="submit">Enregistrer</button>
                        <a class="button button_cancel link" href="../index.php">Annuler</a>
                    </li>
                </ul>
            </fieldset>
            
    </form>

</main>